### ISSUE TITLE
Team members

### ISSUE THREAD

**Issue by Pazzo97** [Pazzo97/TV-Shows#21]
- https://github.com/Pazzo97/JS-Capstone
- We are a group of 2 people as coding partners for the JavaScript capstone project

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly assign all cards to team members and remove tasks related to `Student C` since you are a group of two.

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Pazzo97** [comment]
- Thank you for your review @gemmen29, we did assign the tasks to the student and deleted the tasks related to student C.

**Comment by Omar-Muhamad** [comment]
- [ ] Please assign every kanban card to a certain member for individual tasks and assign both of you to the group tasks.
[Hint] you can do that by clicking on the task itself and a sidebar will appear on the right you can assign any person on any task from the assignee section on that sidebar see the image below.

![image](https://user-images.githubusercontent.com/68796232/168617509-6ee625ec-dcad-45b3-8eac-e09f37c47b19.png)

and you will know it's already assigned from the card itself it will look like the image below.

![image](https://user-images.githubusercontent.com/68796232/168617751-34febe83-90f8-4fc5-ab5c-6de645b6d308.png)

**Comment by omar-muhamad** [comment]
# Changes Required ♻️
### Hi Team,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Changes Required) Aspects to improve: ♻️

-[ ] Please assign every kanban card to a certain member for individual tasks and assign both of you to the group tasks.
[Hint] you can do that by clicking on the task itself and a sidebar will appear on the right you can assign any person on any task from the assignee section on that sidebar see the image below.

![image](https://user-images.githubusercontent.com/68796232/168617509-6ee625ec-dcad-45b3-8eac-e09f37c47b19.png)

and you will know it's already assigned from the card itself it will look like the image below.

![image](https://user-images.githubusercontent.com/68796232/168617751-34febe83-90f8-4fc5-ab5c-6de645b6d308.png)


## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by ShoiraTa** [comment]
## **STATUS: APPROVED  🟢 ** 
------
### Hi team, 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
